# Generated by Django 6.0.6 on 2026-07-08 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavorite',
            name='product',
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='object_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
