# Generated by Django 6.0.6 on 2026-06-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='specialoffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('location', models.CharField()),
                ('link', models.URLField()),
                ('datetime', models.DateTimeField(verbose_name='')),
            ],
        ),
    ]
