# Generated by Django 6.0.6 on 2026-07-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0002_product_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_color',
            name='price',
            field=models.IntegerField(max_length=120, null=True),
        ),
    ]
