# Generated by Django 6.0.6 on 2026-07-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0003_alter_product_color_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_color',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
